name: deploy

on:
  workflow_run:
    workflows: [build]
    types:  [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-success:
    runs-on: ubuntu-latest
    environment: deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Jelastic command
        uses: foodstarter/github-action-jelastic@main
        with:
          jelastic_url: app.my.reclaim.cloud
          jelastic_username: ${{ secrets.RECLAIM_USERNAME }}
          jelastic_password: ${{ secrets.RECLAIM_TOKEN }}
          task: environment/control/redeploycontainerbyid --envName ${{ secrets.RECLAIM_ENV_NAME }} --nodeId ${{ secrets.RECLAIM_NODE_ID }} --tag ${{ env.RECLAIM_DEPLOYMENT_TAG }}